title: Jamie Dalvito
description: Jamie Dalvito - Projects and CV
url: "https://cornell-mae-ug.github.io"
baseurl: "/fa25-portfolio-gjd55"

theme: jekyll-theme-minimal

sass:
  style: compressed

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag